site_name: GaussQuadrature_3dGravity
site_author: Yang
site_url: 
use_directory_urls: false
nav:


     - 主页: index.md



theme: 
  name: material
  language: zh
  palette:
    scheme: default
    primary: deep orange
  features:
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github
  palette: 


    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 亮色模式

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: 暗色模式

extra:
  generator: false
  social:
    - icon: fontawesome/brands/pied-piper-alt
      link: http://how.liheng.work/
    - icon: fontawesome/brands/github
      link: https://github.com/lmliheng

repo_url: https://github.com/https://github.com/PourRevenir/GaussQuadrature_3dGravity
repo_name: GaussQuadrature_3dGravity

copyright: Copyright @2024 GaussQuadrature_3dGravity

markdown_extensions:
  - pymdownx.highlight:

      anchor_linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  